### ISSUE TITLE
Error while training with .tiff files

### ISSUE THREAD

**Issue by alancarlosml** [techzizou/yolov4-custom_Training#1]
Hello,

Thank you for sharing this code.

After run as you described I am getting this following error:

```
Failed to infer label file name (check image extension is supported): /content/drive/MyDrive/CNN_YOLO/NewYOLOv4/darknet/data/obj/train/251_0_2727.tif 
Failed to infer label file name (check image extension is supported): /content/drive/MyDrive/CNN_YOLO/NewYOLOv4/darknet/data/obj/train/32_0_3709.tif 
Failed to infer label file name (check image extension is supported): /content/drive/MyDrive/CNN_YOLO/NewYOLOv4/darknet/data/obj/train/357_0_1629.tif 
Failed to infer label file name (check image extension is supported): /content/drive/MyDrive/CNN_YOLO/NewYOLOv4/darknet/data/obj/train/9_0_3709.tif 
Failed to infer label file name (check image extension is supported): /content/drive/MyDrive/CNN_YOLO/NewYOLOv4/darknet/data/obj/train/268_0_3709.tif 
Failed to infer label file name (check image extension is supported): /content/drive/MyDrive/CNN_YOLO/NewYOLOv4/darknet/data/obj/train/283_0_1629.tif 
 used slow CUDNN algo without Workspace! Need memory: 33359503, available: 13369344
 Try to set subdivisions=64 in your cfg-file. 
 CUDNN-slow CUDA status Error: file: ./src/dark_cuda.c : () : line: 461 : build time: Mar  1 2021 - 01:39:58 

 CUDA Error: out of memory
CUDA Error: out of memory: File exists
darknet: ./src/utils.c:331: error: Assertion `0' failed.
```

However, the image files are presented in the specific folder.

First, I tought that error was due to ".tif" file extension, but I have alread seen YOLO can accept this extension.

I would like to know if the file structure of my project is correct.

![image](https://user-images.githubusercontent.com/413231/109507619-ae609d00-7a7d-11eb-85c9-877999ae7b5c.png)

![image](https://user-images.githubusercontent.com/413231/109507692-bfa9a980-7a7d-11eb-8be4-67d1ae794f8b.png)

![image](https://user-images.githubusercontent.com/413231/109507739-cd5f2f00-7a7d-11eb-90c4-c17d16575f52.png)

![image](https://user-images.githubusercontent.com/413231/109507781-d94af100-7a7d-11eb-823a-d06bec5e802a.png)

![image](https://user-images.githubusercontent.com/413231/109507820-e2d45900-7a7d-11eb-8963-ab114d97f6de.png)

**Comment by techzizou** [comment]
what did you set the subdivisions in the custom cfg file to? that gives Cuda memory error too.. set the subdivisions to 16 or more

**Comment by techzizou** [comment]
ur file structure seems fine. you're also creating the validation images folder which is fine but if you're using the process.py script file that I have given to create the train.txt & test.txt files, make sure to change the ".jpg" in it to ".tif". Just double-check the text files created to verify if they contain the paths to all the images. rest everything should be fine as long as you're following all the basics right.

**Comment by techzizou** [comment]
you're creating both test and valid images folder which is fine but u need just one though, either valid or test. The "obj.data" file needs paths to just train.txt and test.txt.   
Also if you're using the _process.py_ script file that I have given to create the train.txt & test.txt files, make sure to change the ".jpg" in it to ".tif". Just double-check the text files created to verify if they contain the paths to all the images. rest everything should be fine as long as you're following all the basics right.

**Comment by alancarlosml** [comment]
@techzizou Thank you for your reply.

1 - No, I'm not using _process.py_ script to split my dataset. I'm doind this manually.
2 - Ok, I was wrong on _subdivisions_ param, I have set it to 4. I will set it to 16.
3 - train.txt & test.txt files are arealdy with ".tif" extension and the correct full paths to images.
4 - Ok, I will remove the valid folder and references.

**Comment by alancarlosml** [comment]
I made the changes. The error related to _subdivisions_ param was solved.

But the main error still happen.

One important information: when I uploaded the image files to colab, the image names were like this "374.tif_0_3709.tif ", becouse of data augmentation process. Then I renamed them to "374_0_3709.tif" format.

```
Failed to infer label file name (check image extension is supported): /content/drive/MyDrive/CNN_YOLO/NewYOLOv4/darknet/data/obj/train/374_0_3709.tif 
Failed to infer label file name (check image extension is supported): /content/drive/MyDrive/CNN_YOLO/NewYOLOv4/darknet/data/obj/train/274_0_1629.tif 
Loaded: 3.172410 seconds - performance bottleneck on CPU or Disk HDD/SSD
Failed to infer label file name (check image extension is supported): /content/drive/MyDrive/CNN_YOLO/NewYOLOv4/darknet/data/obj/train/59_0_3709.tif 
Failed to infer label file name (check image extension is supported): /content/drive/MyDrive/CNN_YOLO/NewYOLOv4/darknet/data/obj/train/47_0_3709.tif 
v3 (iou loss, Normalizer: (iou: 0.07, obj: 1.00, cls: 1.00) Region 139 Avg (IOU: 0.000000), count: 1, class_loss = 7631.920410, iou_loss = 0.000000, total_loss = 7631.920410 
```

**Comment by techzizou** [comment]
make sure u have changed the name in all locations. in ur image file, its YOLO labeled text file, inside the train.txt or test.txt wherever that augmented image name is.
It definitely is the issue with the filename. ".tif" will work with YOLO that's not the problem. just can't find these images. if you still have a problem post the full error message.

**Comment by alancarlosml** [comment]
@techzizou I have made a double check and everything is ok. 

The full error message is too big to post here, because it doesn't have an end, but I am uploading a .txt. 

I will put some evidences that all is - apparently - correct.

![image](https://user-images.githubusercontent.com/413231/109752694-a3158a80-7bbf-11eb-9a43-06d26abea929.png)
[error.txt](https://github.com/techzizou/yolov4-custom_Training/files/6073583/error.txt)

**Comment by techzizou** [comment]
I tried running .tif and .tiff images. The .tiff ones run fine. However, the .tif images cant run. So , yolo-darknet rt now doesn't work for .tif files.

**Comment by alancarlosml** [comment]
Problem solved. You were right. When I converted from ".tif" to ".tiff" the first error stoped.

But I got other error: Can't open label file. (This can be normal only if you use MSCOCO).

Then I moved all ".txt" from labels folder to obj folder.

Now is running!

Thank you very much!

**Comment by techzizou** [comment]
np. glad I could help
